#!/usr/bin/env bash

creds_path="$1"
terraform_state_path="$2"

cat <<ENVIRONMENT
export BOSH_CLIENT="ci"
export BOSH_CLIENT_SECRET="$(bosh int "$creds_path" --path /ci_secret)"

export BOSH_ENVIRONMENT="$(jq -r .bosh_director_domain "$terraform_state_path")"
export BOSH_CA_CERT="$(bosh int "$creds_path" --path /director_ssl/ca)"
ENVIRONMENT
